steps:
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'create-env']
    env:
      - 'MONGODB_URI=${_MURI}'
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy', 'app1.yaml', '-v', '$_GAE_VERSION']
timeout: '1600s'
